---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-mistral-7b-instruct-v0-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vllm-mistral-7b-instruct-v0-2
  template:
    metadata:
      labels:
        app: vllm-mistral-7b-instruct-v0-2
    spec:
      containers:
      - name: vllm-sim
        image: ghcr.io/llm-d/llm-d-inference-sim:v0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - --model
        - mistralai/Mistral-7B-Instruct-v0.2
        - --port
        - "8000"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
