---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-dynamo-crds
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: dynamo-crds
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: nvidia-dynamo
        namespace: flux-system
      interval: 1h
  install:
    crds: Create
    # strategy:
    #   name: RemediateOnFailure
    #   retryInterval: 5m 
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    # strategy:
    #   name: RemediateOnFailure
    #   retryInterval: 5m 
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: nvidia-dynamo
