---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-dynamo
  namespace: flux-system
spec:
  interval: 10m
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system          
  path: ./infrastructure/controllers/nvidia-dynamo/overlays/staging
  dependsOn:
    - name: nvidia-dynamo-crds