---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-ai-gateway
  namespace: flux-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: envoy-ai-gateway
    namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: Skip
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: envoy-ai-gateway-system
